import type { Metadata } from 'next';
import Image from 'next/image';
import { SiteFooter, SiteHeader } from '../components/site-shell';
import { companions } from '../lib/apps';
import { diaryResources } from '../lib/resources';
import { campaignPlayUrl } from '../lib/customer-start';

export const metadata: Metadata = {
  title: 'Free Diary Resources for Communities and Organisations',
  description: 'Share original blank CuraeVita diary PDFs with your community or readers. Free resources, accurate reusable wording, optional Android app links and no email gate.',
  alternates: { canonical: '/share-resources/' },
  openGraph: { title: 'Share useful blank diaries from CuraeVita', description: 'Free printable resources with clear commercial disclosure and sharing guidance.', url: '/share-resources/' },
};

export default function ShareResources() {
  return <main className="inner-shell"><SiteHeader compact />
    <section className="directory-hero"><p className="eyebrow"><span /> For communities and organisations</p><h1>Share a useful starting point.</h1><p>Original blank A4 diaries for your readers, members or visitors. No payment, email address or app subscription is required to download the templates.</p><p>CuraeVita is a commercial app developer. Its Android apps are optional, separate paid subscriptions. Sharing a blank diary does not imply your endorsement of an app or a treatment.</p><a className="button button-primary" href="/resources/">Download the five free diaries →</a></section>
    <section className="guide-directory growth-card-grid" aria-label="Resources you can share">{diaryResources.map(resource => { const app = companions.find(item => item.slug === resource.slug)!; return <article className="guide-card" key={resource.id}><Image src={app.image} alt="" width={56} height={56} /><p className="card-kicker">Free blank PDF</p><h2>{resource.title}</h2><p>{resource.description}</p><div className="resource-links"><a className="button button-primary" href={`/downloads/${resource.id}-diary.pdf`} download>Download blank diary ↓</a><a className="text-link" href={`/resources/#${resource.id}`}>Public resource link →</a><a className="text-link" href={campaignPlayUrl(app.storeUrl!, 'resource_partner', app.slug)}>Optional paid Android app ↗</a></div></article>; })}</section>
    <section className="content-section"><div className="content-heading"><p className="eyebrow"><span /> Suggested wording</p><h2>A factual description you can reuse.</h2></div><blockquote className="resource-quote">CuraeVita offers five free printable diaries for GLP-1 injection records, menopause symptoms, ADHD medication records, meals and digestive observations, and migraine attacks. No sign-up is required. These are personal record templates, not medical advice. CuraeVita also sells optional Android apps with separate £0.99/month UK subscriptions after eligible seven-day trials. Local prices and eligibility vary; subscriptions renew unless cancelled in Google Play. Free templates: https://curaevita.com/resources/</blockquote></section>
    <section className="content-section faq-section"><div className="content-heading"><p className="eyebrow"><span /> Sharing responsibly</p><h2>Keep the resource useful and honest.</h2></div><div className="faq-list"><details><summary>May an organisation print the diaries?</summary><p>Yes. Print and share the original blank templates, retaining the CuraeVita attribution and limitations. Do not sell the templates, imply clinical endorsement, or distribute completed diaries.</p></details><details><summary>May I post the link in a group?</summary><p>Only if the group rules permit it and, where required, an administrator approves. Disclose any connection to CuraeVita. Do not contact members privately because of a health condition or add them to a mailing list.</p></details><details><summary>Does CuraeVita receive completed records?</summary><p>No completed record is submitted by downloading the blank PDF. Keep completed copies private. Neither this page nor the templates asks for patient information.</p></details><details><summary>Are these clinically validated treatment tools?</summary><p>They are personal diaries, not diagnostic tests, treatment recommendations or emergency monitors. Sharing them does not imply clinical validation or endorsement.</p></details></div></section>
    <aside className="share-section"><div><p className="eyebrow"><span /> Resource enquiries</p><h2>Ask a practical question.</h2><p>For permission or accessibility questions, contact the CuraeVita team. Please do not send patient details.</p></div><a className="button button-primary" href="mailto:eliviontechnologies@gmail.com?subject=CuraeVita%20free%20resource%20enquiry">Email the team</a></aside><SiteFooter />
  </main>;
}
